import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { ContextOverAll } from "@/components/context/Context";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { Toaster } from "react-hot-toast";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Table",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <ContextOverAll>
          <Header />
          <Toaster position="top-right" />
          {children}
          <Footer />
        </ContextOverAll>
      </body>
    </html>
  );
}
